[semantic_release]
commit_parser = 'commit_parser:TRVCommitParser'
commit_message = "REL: Bump version to {version}"
tag_format = 'v{version}'
allow_zero_version = true
major_on_zero = false
no_git_verify = false
logging_use_named_masks = false

[semantic_release.branches.main]
match = 'main'
prerelease = false

[semantic_release.changelog]
template_dir = "deploy/pkg/templates"
exclude_commit_patterns = ['\[gh-actions\]', '\[pre-commit.ci\]',]

[semantic_release.changelog.environment]
block_start_string = '{%'
block_end_string = '%}'
variable_start_string = '{{'
variable_end_string = '}}'
comment_start_string = '{#'
comment_end_string = '#}'
newline_sequence = "\n"
autoescape = true
trim_blocks = false
lstrip_blocks = false
keep_trailing_newline = false

[tool.semantic_release.commit_author]
env = 'GIT_COMMIT_AUTHOR'
default = "semantic-release <semantic-release>"
